### ISSUE TITLE
训练完成后使用时爆显存的问题 

### ISSUE THREAD

**Issue by FeiXie8** [shaofengzeng/SuperPoint-Pytorch#10]
作者您好！我在训练完成后使用Superpoint推断时发现即使设置了with torch.no_grad():，当我连续推断两张图片时显存溢出，并且速度很慢，一张480p的图片放在gpu上需要1s
`device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
    # device='cpu'
    net = SuperPointBNNet(config['model'], device=device, using_bn=config['model']['using_bn'])
    net.load_state_dict(torch.load(config['model']['pretrained_model'],map_location=device))
    net.to(device).eval()

    example = cv2.imread("/home/xiefei/COCO_test2014_000000000001.jpg",0)
    img_tensor = torch.as_tensor(example.copy(), dtype=torch.float, device=device)
    img_tensor=img_tensor/255.
    img_tensor=img_tensor.unsqueeze(0)
    img_tensor=img_tensor.unsqueeze(0)

    with torch.no_grad():
        t1=time.time()
        output=net(img_tensor)
        t2=time.time()
        print(t2-t1)`

**Comment by shaofengzeng** [comment]
您好，您提到的这个问题我确实没有遇到过，从代码上也看不出有什么问题。你可以单步调试一下，定义为下具体位置。如果有必要，可以先将device设置为cpu

**Comment by shaofengzeng** [comment]
您好，您提到的问题我确实没有遇到过，从代码上也看不出有什么问题。你可以单步调试一下，定义为下具体位置。如果有必要，可以先将device设置为cpu

**Comment by FeiXie8** [comment]
> 您好，您提到的这个问题我确实没有遇到过，从代码上也看不出有什么问题。你可以单步调试一下，定义为下具体位置。如果有必要，可以先将device设置为cpu

我也尝试了很多遍，但是和原论文中能达到72fps on cpu还差距较大，请问你的帧率能达到多少呢，我现在可能只有10fps左右

**Comment by shaofengzeng** [comment]
您好，爆内存的问题是解决了吗？关于速度，我确实没有做优化，也没有测试。如果训练好模型后，做前向传播，可以精简一下算法，包括合理分配cpu，gpu算力，数据输入(不需要预处理)，简化模型输出(目前会输出多个结果)等，具体可参考magicleap公开的代码。做好优化以后应该是没有问题的。

**Comment by FeiXie8** [comment]
> 您好，爆内存的问题是解决了吗？关于速度，我确实没有做优化，也没有测试。如果训练好模型后，做前向传播，可以精简一下算法，包括合理分配cpu，gpu算力，数据输入(不需要预处理)，简化模型输出(目前会输出同类型的多种不同的结果)等，具体可参考magicleap公开的代码。做好优化以后应该是没有问题的。

我试了magic公开的代码，如果输入是320p，帧率只有5帧，这种运行速度感觉没法实际用啊，除非把输入图像resize成[160,120]

**Comment by FeiXie8** [comment]
> 您好，爆内存的问题是解决了吗？关于速度，我确实没有做优化，也没有测试。如果训练好模型后，做前向传播，可以精简一下算法，包括合理分配cpu，gpu算力，数据输入(不需要预处理)，简化模型输出(目前会输出同类型的多种不同的结果)等，具体可参考magicleap公开的代码。做好优化以后应该是没有问题的。

其实预处理占用时间很少的，还有我不明白目前会输出同种类型不同结果是什么意思，我看了不就只有关键点和描述符吗
