### ISSUE TITLE
Inference or demo codes using the pretrained models?

### ISSUE THREAD

**Issue by ZhangGongjie** [shaofengzeng/SuperPoint-Pytorch#12]
Hi, fantastic work done! Applause for you!!

May I know if there is any instruction or codes for a quick demo using pre-trained models? Thank you in advance!

Also, may I know: between the weight released by magicleap and the weight released by rpautrat's superpoint, which one has better performance?

**Comment by zhoulikeda** [comment]
> Hi, here is a model i trained before，and you can test it by the file _compute_desc_eval.py_ [sp_0](https://pan.baidu.com/s/10pktUYScMmGbnZxTJVDDHw) code: r52r However, it may not be the best model, only for your demo.
> 
> It seems that rpautrat's superpoint usually show better performances (according to these [results](https://github.com/rpautrat/SuperPoint))

The link of sp_0 expired, why not put it on git?
