### ISSUE TITLE
color input

### ISSUE THREAD

**Issue by zebin-dm** [shaofengzeng/SuperPoint-Pytorch#13]
Hello, thanks for your promising job. would you has planed to implemented rgb  color instead of gray input.

**Comment by shaofengzeng** [comment]
I think it is easy to change the input gray image to a color one. The main problem is to modify the image augmentation methods in `photometric_augmentation.py`, you can refer to this [repo.](https://hub.nuaa.cf/eric-yyjau/pytorch-superpoint) ,or write these methods with the help of [imgaug](https://hub.nuaa.cf/aleju/imgaug). Some other methods, like `ratio_preserving_resize` , are also need minor modifications.

**Comment by zebin-dm** [comment]
> 

thanks for you reply. i has rewrite this repo to support rgb input. the training process convergence quick and has a more lower loss value.  but the evaluation result is quite bad.

**Comment by shaofengzeng** [comment]
> > 
> 
> thanks for you reply. i has rewrite this repo to support rgb input. the training process convergence quick and has a more lower loss value. but the evaluation result is quite bad.

I suggest checking the input data. Make sure they are consistent with the training stage.
