### ISSUE TITLE
transfer learning 

### ISSUE THREAD

**Issue by Lucifer1002** [shaofengzeng/SuperPoint-Pytorch#14]
How to do transfer learning on top of your pretrained model？

**Comment by shaofengzeng** [comment]
You can use the model [superpoint_bn.pth](https://github.com/shaofengzeng/SuperPoint-Pytorch/blob/master/superpoint_bn.pth), or [superpoint_v1.pth](https://github.com/shaofengzeng/SuperPoint-Pytorch/blob/master/superpoint_v1.pth) as pretrained model. All you need to do is set the path of the pretrained model to `pretrained_model` in `*.yaml`. However, i think there is no need to use the pretrained model, it is quite easy to converge.

**Comment by shaofengzeng** [comment]
You can set the path of pretrained model, [superpoint_v1.pth](https://github.com/shaofengzeng/SuperPoint-Pytorch/blob/master/superpoint_v1.pth) or [superpoint_bn.pth](https://github.com/shaofengzeng/SuperPoint-Pytorch/blob/master/superpoint_bn.pth), to `pretrained_model` in `*.yaml`. However, i think there is no need to use transfer learning, it is quite easy to converge.
