### ISSUE TITLE
Matching

### ISSUE THREAD

**Issue by Lucifer1002** [shaofengzeng/SuperPoint-Pytorch#15]
How does the trained Superpoint model combine with Superglue to achieve image matching?

**Comment by shaofengzeng** [comment]
> How does the trained Superpoint model combine with Superglue to achieve image matching?

You have to write the training code for superglue. Please refer to [SuperGlue](https://hub.nuaa.cf/magicleap/SuperGluePretrainedNetwork) or [SuperGlue-pytorch](https://hub.nuaa.cf/HeatherJiaZG/SuperGlue-pytorch)

**Comment by jeannotes** [comment]
sorry, https://hub.nuaa.cf/HeatherJiaZG/SuperGlue-pytorch? seems can not open it

**Comment by shaofengzeng** [comment]
> sorry, https://hub.nuaa.cf/HeatherJiaZG/SuperGlue-pytorch? seems can not open it

Search "SuperGlue" in Github
