### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by stragerrr** [shaofengzeng/SuperPoint-Pytorch#16]
How to train with Superpoint instead of Superpoint_BN？

**Comment by shaofengzeng** [comment]
> How to train with Superpoint instead of Superpoint_BN？

Set ```using_bn: false``` in *.yaml files

**Comment by stragerrr** [comment]
好的，十分感谢

**Comment by stragerrr** [comment]
Hello, thank you for your answer, when was the last time there is a problem is that I use your training network training superpoint successful model, applied directly to SuperGluePretrainedNetwork will appear model mismatch phenomenon, how to solve this problem?

**Comment by shaofengzeng** [comment]
> Hello, thank you for your answer, when was the last time there is a problem is that I use your training network training superpoint successful model, applied directly to SuperGluePretrainedNetwork will appear model mismatch phenomenon, how to solve this problem?

I think you have to train a new superglue for your superpoint...
