### ISSUE TITLE
README.md 中的 Usage 中是否有几个错误

### ISSUE THREAD

**Issue by ZhihangCui** [shaofengzeng/SuperPoint-Pytorch#19]
首先感谢您的工作
我是一个深度学习新手
我在阅读 README.md 时，发现可能存在一些笔误，虽然不影响代码的运行，但是给我带来了一些困扰，比如
Usage 2.0 中表述的 in train.py, line 61，实际上由于代码改动，好像不在那一行了。
2.4 和 2.6 中的 python train.py ./config/magic_point_coco_train.py #with correct data dirs 和 python train.py ./config/superpoint_train.py #with correct data dirs 表述的 ./config/*.py 是否应为 ./config/*.yaml 。

**Comment by shaofengzeng** [comment]
已经进行修正，非常感谢您的建议

**Comment by ZhihangCui** [comment]
> 已经进行修正，非常感谢您的建议
可能还存在一个错误：
2.2 Train MagicPoint (>1 hours):
python train.py ./config/magic_point_train.yaml
(Note that you have to delete the directory ./data/synthetic_shapes whenever you want to regenerate it)
其中
./config/magic_point_train.yaml
已经不存在了，是改成了./config/magic_point_syn_train.yaml了吗

**Comment by shaofengzeng** [comment]
> > 已经进行修正，非常感谢您的建议
> > 可能还存在一个错误：
> > 2.2 Train MagicPoint (>1 hours):
> > python train.py ./config/magic_point_train.yaml
> > (Note that you have to delete the directory ./data/synthetic_shapes whenever you want to regenerate it)
> > 其中
> > ./config/magic_point_train.yaml
> > 已经不存在了，是改成了./config/magic_point_syn_train.yaml了吗

是的，应该将magic_point_train.yaml 修改为 magic_point_syn_train.yaml。已更正。
