### ISSUE TITLE
关于magicpoint是否只是用来生成coco label数据集？

### ISSUE THREAD

**Issue by atomishcv** [shaofengzeng/SuperPoint-Pytorch#21]
您好！因为我想改superpoint的网络结构，我想问magicpoint是否只是用来生成coco label的数据集呢？如果magicpoint和superpoint的网络结构不同是否会对训练的结果有影像呢？

**Comment by shaofengzeng** [comment]
magicpoint结构可以和superpoint不同，superpoint训练可以不需要加载预训练模型...

**Comment by shaofengzeng** [comment]
magicpoint结构可以和superpoint不同，superpoint训练可以不加载预训练模型...

**Comment by atomishcv** [comment]
谢谢！
