### ISSUE TITLE
multi GPU train

### ISSUE THREAD

**Issue by RaneWouters** [shaofengzeng/SuperPoint-Pytorch#23]
How should I modify the code to conduct multi GPU training? At the end of train.py file the following code is added before train_eval(model, data_loaders, config) function.
```
if torch.cuda.device_count() > 1: 
    model = torch.nn.DataParallel(model, device_ids=list(range(torch.cuda.device_count()))
model.to(device)
```

After that, When I train the code, I get the following messages.

```
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    train_eval(model, data_loaders, config)
  File "train.py", line 84, in train_eval
    prob_warp, desc_warp, device)
  File "/root/Source/gtr/SuperPoint_pytorch/temp/SuperPoint-Pytorch-master/solver/loss.py", line 16, in loss_func
    device=device)
  File "/root/Source/gtr/SuperPoint_pytorch/temp/SuperPoint-Pytorch-master/solver/loss.py", line 65, in detector_loss
    ce_loss = F.cross_entropy(logits, labels, reduction='none',)
  File "/root/PersonalData/miniconda/envs/superpoint/lib/python3.7/site-packages/torch/nn/functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (16) to match target batch_size (64).
```
It seems to be the problem of data set allocation under multi GPU training. But I don't know how to modify it.

**Comment by shaofengzeng** [comment]
Here is [tutorial](https://www.bilibili.com/video/BV1yt4y1e7sZ/?spm_id_from=333.337.search-card.all.click&vd_source=fe3271b1b2665f296de2ea413870a362)

**Comment by RaneWouters** [comment]
thanks very much for your tutorial. I have solved this problem through this video.

**Comment by kaiyi98** [comment]
> thanks very much for your tutorial. I have solved this problem through this video.

Hello, I want to konw how to solved the problem. It seem that the data is a dictionary and it can not ".to(device)" so that can not split it to multi-gpus.

I can't solve it.
