### ISSUE TITLE
Crop in augmentation_legacy.py

### ISSUE THREAD

**Issue by hjr553199215** [shaofengzeng/SuperPoint-Pytorch#5]
请问在dataset/utils/augmentation_legacy.py文件的elastic_transform函数中为什么会按照如下的方式定义min_row,max_row,min_col,max_col
    min_row = int(math.ceil(np.max(dy))) + padding   
    max_row = int(math.floor(np.min(dy))) + shape[0] - padding   
    min_col = int(math.ceil(np.max(dx))) + padding
    max_col = int(math.floor(np.min(dx))) + shape[1] - padding

**Comment by shaofengzeng** [comment]
您好，这部分代码是直接从rpautrat/SuperPoint的代码中拷贝的，我并没有做过多修改，也没有深入研究过。但代码目的是对图像进行随机变化，所以并没有标准的变化方式，原理上你可以更改这种随机变化的方式，但要确保变化种类、变化幅度是在网络学习能力范围之内的。
