### ISSUE TITLE
Cuda： out of memory

### ISSUE THREAD

**Issue by hjr553199215** [shaofengzeng/SuperPoint-Pytorch#9]
作者您好，近期在遵循您给出的训练步骤进行复现时，发现如果将输入图片尺寸修改为[480, 640]，则代码将无法正常工作，并提示显存不足，我目前所采用的设备是2080Ti显卡，8G显存，因为我个人觉得依照这个网络模型，[480,640]的图片尺寸不应该出现超出8G显存的问题，针对超出显存的报错，我不知道问题出在了哪里，我在训练的过程中即使将batch_size修改为1仍然会提示超出显存，所以想请教一下您，为什么网络面向[480,640]的图片尺寸时即使batch_size为1还会出现显存不够的问题呢？期待您的回复

**Comment by shaofengzeng** [comment]
您好，8G内存确实少了，母前12G内存也就是跑batch size也就是设置为2，再大也跑不动。前向传播内存占用很少，但是训练的时候，特别是计算特征描述损失时，会消耗较大资源，若干变量会占用B*(H/8)*(W/8)*(H/8)*(W/8)大小的内存，当H=480，W=640时，这个内存占用就非常大了，详细请参考代码descriptor_loss.
